# Generated by Django 3.2.9 on 2021-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_portfolioimg_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
