# Generated by Django 3.2.9 on 2021-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_home_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
