# Generated by Django 3.2.9 on 2021-12-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20211211_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img1',
            field=models.ImageField(default=1, upload_to='my-photes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='img2',
            field=models.ImageField(default=1, upload_to='my-photes/'),
            preserve_default=False,
        ),
    ]
